FROM hongzezhang/gluten-build:latest AS gluten-tpc
MAINTAINER Hongze Zhang<hongze.zhang@intel.com>

SHELL ["/bin/bash", "-c"]

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends ssh net-tools vim unzip libjemalloc-dev

ARG GLUTEN_IT_REPO
ARG GLUTEN_IT_COMMIT

RUN test -n "$GLUTEN_IT_REPO" || (echo "GLUTEN_IT_REPO not set" && false)
RUN test -n "$GLUTEN_IT_COMMIT" || (echo "GLUTEN_IT_COMMIT not set" && false)

RUN cd /opt/ \
    && git clone $GLUTEN_IT_REPO gluten-it

RUN cd /opt/gluten-it \
    && git fetch origin $GLUTEN_IT_COMMIT:build_$GLUTEN_IT_COMMIT \
    && git checkout build_$GLUTEN_IT_COMMIT

ARG BUILD_BACKEND_TYPE

RUN test -n "$BUILD_BACKEND_TYPE" || (echo "BUILD_BACKEND_TYPE not set" && false)

RUN if [ "$BUILD_BACKEND_TYPE" == "velox" ]; \
    then \
      GLUTEN_IT_MAVEN_OPTIONS="-Pspark-3.2 -Pgluten-velox -Darrow.version=10.0.0-SNAPSHOT"; \
    elif [ "$BUILD_BACKEND_TYPE" == "gazelle-cpp" ]; \
    then \
      GLUTEN_IT_MAVEN_OPTIONS="-Pspark-3.2 -Pgluten-gazellecpp -Darrow.version=8.0.0-gluten-SNAPSHOT"; \
    else \
      echo "Unrecognizable backend type: $BUILD_BACKEND_TYPE"; \
      exit 1; \
    fi && echo $GLUTEN_IT_MAVEN_OPTIONS > ~/.gluten-it-mvn-options;

RUN GLUTEN_IT_MAVEN_OPTIONS=$(cat ~/.gluten-it-mvn-options) \
    && cd /opt/gluten-it \
    && bash -c "mvn clean package $GLUTEN_IT_MAVEN_OPTIONS"

FROM gluten-tpc AS gluten-tpc-gdb

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends gdb

FROM gluten-tpc-gdb AS gluten-tpc-gdb-server

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends gdbserver

# EOF
