FROM hongzezhang/gluten-build:latest AS gluten-tpc
MAINTAINER Hongze Zhang<hongze.zhang@intel.com>

SHELL ["/bin/bash", "-c"]

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends ssh net-tools vim unzip libjemalloc-dev

ARG BUILD_BACKEND_TYPE

RUN test -n "$BUILD_BACKEND_TYPE" || (echo "BUILD_BACKEND_TYPE not set" && false)

RUN if [ "$BUILD_BACKEND_TYPE" == "velox" ]; \
    then \
      GLUTEN_IT_MAVEN_OPTIONS="-Pspark-3.2 -Pgluten-velox -Darrow.version=10.0.0-SNAPSHOT"; \
            ./ep/build-arrow/src/get_arrow.sh  \
      && ./ep/build-arrow/src/build_arrow_for_velox.sh \
      && /ep/build-velox/src/get_velox.sh \
      && ./ep/build-velox/src/build_velox.sh --build_protobuf=ON --build_folly=ON
    elif [ "$BUILD_BACKEND_TYPE" == "gazelle-cpp" ]; \
    then \
      GLUTEN_IT_MAVEN_OPTIONS="-Pspark-3.2 -Pgluten-gazellecpp -Darrow.version=8.0.0-gluten-SNAPSHOT"; \
      && ./ep/build-arrow/src/get_arrow.sh --arrow_branch=arrow-8.0.0-gluten-20220427a\
      && ./ep/build-arrow/src/build_arrow_for_gazelle.sh
    else \
      echo "Unrecognizable backend type: $BUILD_BACKEND_TYPE"; \
      exit 1; \
    fi && echo $GLUTEN_IT_MAVEN_OPTIONS > ~/.gluten-it-mvn-options;

RUN GLUTEN_IT_MAVEN_OPTIONS=$(cat ~/.gluten-it-mvn-options) \
    && cd /opt/gluten/tools/gluten-it \
    && bash -c "mvn clean package $GLUTEN_IT_MAVEN_OPTIONS"

FROM gluten-tpc AS gluten-tpc-gdb

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends gdb

FROM gluten-tpc-gdb AS gluten-tpc-gdb-server

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends gdbserver

# EOF
