FROM centos:7

RUN sed -i -e "s|mirrorlist=|#mirrorlist=|g" /etc/yum.repos.d/CentOS-* || true
RUN sed -i -e "s|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g" /etc/yum.repos.d/CentOS-* || true

RUN yum install -y centos-release-scl
RUN rm /etc/yum.repos.d/CentOS-SCLo-scl.repo -f
RUN sed -i \
       -e 's/^mirrorlist/#mirrorlist/' \
       -e 's/^#baseurl/baseurl/' \
       -e 's/mirror\.centos\.org/vault.centos.org/' \
       /etc/yum.repos.d/CentOS-SCLo-scl-rh.repo

RUN yum install -y git patch wget sudo java-1.8.0-openjdk-devel

# build
RUN git clone --depth=1 https://github.com/apache/incubator-gluten /opt/gluten

RUN echo "check_certificate = off" >> ~/.wgetrc
# deps
RUN cd /opt/gluten && bash ./dev/vcpkg/setup-build-depends.sh

# vcpkg env
ENV VCPKG_BINARY_SOURCES=clear;files,/var/cache/vcpkg,readwrite

RUN cd /opt/gluten && source ./dev/vcpkg/env.sh && \
    bash ./dev/builddeps-veloxbe.sh --build_arrow=ON
