[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "gluten" 
version = "1.1.0"

[tool.setuptools.packages.find]
where = ["src"] 

[tool.setuptools.package-data]
"*" = ["*.*"] 
