# Copyright (c) Facebook, Inc. and its affiliates.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
name: macOS Build

on:
  pull_request:
    paths:
      - '.github/workflows/macos.yml'
      - 'pom.xml'
      - 'backends-velox/**'
      - 'gluten-uniffle/**'
      - 'gluten-celeborn/**'
      - 'gluten-ras/**'
      - 'gluten-core/**'
      - 'gluten-substrait/**'
      - 'gluten-arrow/**'
      - 'gluten-delta/**'
      - 'gluten-iceberg/**'
      - 'gluten-hudi/**'
      - 'gluten-ut/**'
      - 'shims/**'
      - 'tools/gluten-it/**'
      - 'ep/build-velox/**'
      - 'cpp/**'
      - 'dev/**'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.repository }}-${{ github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  macos-build:
    # if: ${{ github.repository == 'facebookincubator/velox' }}
    name: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # macos-15 = arm64 Mac and cmake 4.0
        os: [macos-15]
    runs-on: ${{ matrix.os }}
    env:
      CCACHE_DIR: ${{ github.workspace }}/ccache
      # The arm runners have only 7GB RAM
      BUILD_TYPE: ${{ matrix.os == 'macos-15' && 'Release' || 'Debug' }}
      INSTALL_PREFIX: /tmp/deps-install
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install Dependencies
        env:
          HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 'TRUE'
          CMAKE_POLICY_VERSION_MINIMUM: '3.5'
        run: |
          echo "NJOBS=`sysctl -n hw.ncpu`" >> $GITHUB_ENV
          brew install wget pkgconfig
          brew install --cask zulu@8
          echo 'export JAVA_HOME=`/usr/libexec/java_home -v 1.8`' >> ~/.zshrc
          echo "$(echo $USERNAME) ALL=(ALL:ALL) NOPASSWD:ALL" | EDITOR='tee -a' sudo visudo

      - name: Cache ccache
        uses: apache/infrastructure-actions/stash/restore@3354c1565d4b0e335b78a76aedd82153a9e144d4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-macos-1-${{ matrix.os }}

      - name: Build
        run: |
          ./dev/buildbundle-veloxbe.sh --run_setup_script=ON --build_arrow=ON --build_tests=ON

      - uses: apache/infrastructure-actions/stash/save@3354c1565d4b0e335b78a76aedd82153a9e144d4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-macos-1-${{ matrix.os }}
