# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Upload docs to apache nightly

on:
  pull_request:
    paths:
      - 'docs/**'
      - '.github/workflows/nightly_sync.yml'
jobs:

  script-change-test:
    name: check Velox script change and build docker image if needed
    runs-on: ubuntu-latest
    steps:
      - name: Check if scripts changed
        run: |
          git clone --depth 10 --branch main https://github.com/facebookincubator/velox.git velox
          cd velox
          if [[ $(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep -E '(^|/)scripts/.*') ]]; then
            echo "Scripts changed, run gpu-docker-tests"
          else
            echo "No script changes, skip gpu-docker-tests"
            exit 0
          fi
      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Check CI Status
        # Allow manual triggered workflows to circumvent the check
        if: ${{ github.event_name != 'workflow_dispatch' }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh workflow run ./.github/workflows/docker_image.yml -f job_to_run=build-centos-9-jdk8-cudf

  upload_to_nightlies:
    if: ${{ startsWith(github.repository, 'apache/') }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: build doc
        uses: actions/jekyll-build-pages@v1
      - name: rsync
        uses: burnett01/rsync-deployments@0dc935cdecc5f5e571865e60d2a6cdc673704823
        with:
          switches: -avzr --delete
          path: _site
          remote_path: ${{ secrets.NIGHTLIES_RSYNC_PATH }}/gluten/docs/
          remote_host: ${{ secrets.NIGHTLIES_RSYNC_HOST }}
          remote_port: ${{ secrets.NIGHTLIES_RSYNC_PORT }}
          remote_user: ${{ secrets.NIGHTLIES_RSYNC_USER }}
          remote_key: ${{ secrets.NIGHTLIES_RSYNC_KEY }}
