# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Velox backend 

on:
  pull_request:
    paths:
      - '.github/**'
      - 'pom.xml'
      - 'backends-velox/**'
      - 'gluten-celeborn/**'
      - 'gluten-core/**'
      - 'gluten-data/**'
      - 'gluten-delta/**'
      - 'gluten-iceberg/**'
      - 'gluten-ut/**'
      - 'shims/**'
      - 'tools/gluten-it/**'
      - 'tools/gluten-te/**'
      - 'ep/build-velox/**'
      - 'cpp/*'
      - 'cpp/CMake/**'
      - 'cpp/velox/**'
      - 'cpp/core/**'
      - 'dev/**'


concurrency:
  group: ${{ github.repository }}-${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-docker:
    runs-on: ubuntu-20.04
    container: inteldpo/gluten-centos-packaging:latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Gluten velox third party
        run: |
          yum install sudo patch java-1.8.0-openjdk-devel -y && \
          cd $GITHUB_WORKSPACE/ep/build-velox/src && \
          ./get_velox.sh && \
          source /opt/rh/devtoolset-9/enable && \
          source /opt/gluten/dev/vcpkg/env.sh && \
          cd $GITHUB_WORKSPACE/ && \
          ./dev/buildbundle-veloxbe.sh --build_tests=ON --build_benchmarks=ON --enable_s3=ON  --enable_hdfs=ON
      - name: Build Gluten CPP library
        run: |
          cd $GITHUB_WORKSPACE/cpp && \
          source /opt/rh/devtoolset-9/enable && \
          ./compile.sh --build_velox_backend=ON --build_protobuf=ON
      - name: Build for Spark 3.2.2
        run: |
          wget https://downloads.apache.org/maven/maven-3/3.8.8/binaries/apache-maven-3.8.8-bin.tar.gz && \
          tar -xvf apache-maven-3.8.8-bin.tar.gz && \
          mv apache-maven-3.8.8 /usr/lib/maven && \
          export MAVEN_HOME=/usr/lib/maven && \
          export PATH=${PATH}:${MAVEN_HOME}/bin && \
          cd $GITHUB_WORKSPACE/ && \
          mvn clean install -Pspark-3.2 -Pbackends-velox -DskipTests
      - name: Build and run TPCH/DS 3.2.2
        run: |
          cd $GITHUB_WORKSPACE/tools/gluten-it && \
          export MAVEN_HOME=/usr/lib/maven && \
          export PATH=${PATH}:${MAVEN_HOME}/bin && \
          mvn clean install -Pspark-3.2 \
          && GLUTEN_IT_JVM_ARGS=-Xmx5G sbin/gluten-it.sh queries-compare \
            --local --preset=velox --benchmark-type=h --error-on-memleak --off-heap-size=10g -s=1.0 --threads=16 --iterations=1 \
          && GLUTEN_IT_JVM_ARGS=-Xmx5G sbin/gluten-it.sh queries-compare \
            --local --preset=velox --benchmark-type=ds --error-on-memleak --off-heap-size=10g -s=1.0 --threads=16 --iterations=1