# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Velox backend Github Runner

on:
  pull_request:
    paths:
      - '.github/workflows/velox_docker.yml'
      - 'pom.xml'
      - 'backends-velox/**'
      - 'gluten-uniffle/**'
      - 'gluten-celeborn/common/**'
      - 'gluten-celeborn/package/**'
      - 'gluten-celeborn/velox/**'
      - 'gluten-ras/**'
      - 'gluten-core/**'
      - 'gluten-data/**'
      - 'gluten-delta/**'
      - 'gluten-iceberg/**'
      - 'gluten-ut/**'
      - 'shims/**'
      - 'tools/gluten-it/**'
      - 'tools/gluten-te/**'
      - 'ep/build-velox/**'
      - 'cpp/*'
      - 'cpp/CMake/**'
      - 'cpp/velox/**'
      - 'cpp/core/**'
      - 'dev/**'


concurrency:
  group: ${{ github.repository }}-${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-native-lib-centos-7:
    runs-on: ubuntu-20.04
    container: apache/gluten:gluten-vcpkg-builder_2024_03_17 # centos7 with dependencies installed
    steps:
      - uses: actions/checkout@v2
      - name: Generate cache key
        run: |
          echo ${{ hashFiles('./ep/build-velox/src/**', './dev/**', './cpp/*', './github/workflows/*') }} > cache-key
      - name: Cache
        id: cache
        uses: actions/cache/restore@v3
        with:
          path: ./cpp/build/releases/
          key: cache-velox-build-${{ hashFiles('./cache-key') }}
      - name: Build Gluten Velox third party
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        run: |
          source dev/ci-velox-buildstatic.sh
      - uses: actions/upload-artifact@v2
        with:
          path: ./cpp/build/releases/
          name: velox-native-lib-centos-7-${{github.sha}}

  run-spark-test-spark32:
    needs: build-native-lib-centos-7
    runs-on: ubuntu-20.04
    container: ghcr.io/facebookincubator/velox-dev:circleci-avx
    env:
      CCACHE_DIR: "${{ github.workspace }}/.ccache"
    steps:
      - uses: actions/checkout@v2
      - name: Download All Artifacts
        uses: actions/download-artifact@v2
        with:
          name: velox-native-lib-centos-7-${{github.sha}}
          path: ./cpp/build/releases
      - name: Setup build dependency
        run: |
          yum install sudo patch java-1.8.0-openjdk-devel wget -y
          wget https://downloads.apache.org/maven/maven-3/3.8.8/binaries/apache-maven-3.8.8-bin.tar.gz
          tar -xvf apache-maven-3.8.8-bin.tar.gz
          mv apache-maven-3.8.8 /usr/lib/maven
          echo "PATH=${PATH}:/usr/lib/maven/bin" >> $GITHUB_ENV
      - name: Get Ccache
        uses: actions/cache/restore@v3
        with:
          path: '${{ env.CCACHE_DIR }}'
          key: ccache-centos-release-default
      - name: Ensure Cache Dirs Exists
        working-directory: ${{ github.workspace }}
        run: |
          mkdir -p '${{ env.CCACHE_DIR }}'
      - name: Gluten CPP Test
        run: |
          cd $GITHUB_WORKSPACE/cpp/build && \
          ctest -V
      - name: Prepare spark.test.home for Spark 3.2.2 (other tests)
        run: |
          cd $GITHUB_WORKSPACE/ && \
          wget https://archive.apache.org/dist/spark/spark-3.2.2/spark-3.2.2-bin-hadoop3.2.tgz && \
          tar --strip-components=1 -xf spark-3.2.2-bin-hadoop3.2.tgz spark-3.2.2-bin-hadoop3.2/jars/ && \
          rm -rf spark-3.2.2-bin-hadoop3.2.tgz && \
          mkdir -p $GITHUB_WORKSPACE//shims/spark32/spark_home/assembly/target/scala-2.12 && \
          mv jars $GITHUB_WORKSPACE//shims/spark32/spark_home/assembly/target/scala-2.12 && \
          cd $GITHUB_WORKSPACE// && \
          wget https://github.com/apache/spark/archive/refs/tags/v3.2.2.tar.gz && \
          tar --strip-components=1 -xf v3.2.2.tar.gz spark-3.2.2/sql/core/src/test/resources/  && \
          mkdir -p shims/spark32/spark_home/ && \
          mv sql shims/spark32/spark_home/ && \
          dnf module -y install python39 && \
          alternatives --set python3 /usr/bin/python3.9 && \
          pip3 install pyspark==3.2.2 cython && \
          pip3 install pandas pyarrow
      - name: Build and run unit test for Spark 3.2.2 (other tests)
        run: |
          cd $GITHUB_WORKSPACE/
          export SPARK_SCALA_VERSION=2.12
          mvn -ntp clean install -Pspark-3.2 -Pspark-ut -Pbackends-velox -Pceleborn -Piceberg -Pdelta -DargLine="-Dspark.test.home=$GITHUB_WORKSPACE//shims/spark32/spark_home/" -DtagsToExclude=org.apache.spark.tags.ExtendedSQLTest,org.apache.gluten.tags.UDFTest,org.apache.gluten.tags.SkipTestTags && \
          mvn -ntp test -Pspark-3.2 -Pbackends-velox -Piceberg -Pdelta -DtagsToExclude=None -DtagsToInclude=org.apache.gluten.tags.UDFTest
      - name: Upload golden files
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: golden-files-spark32
          path: /tmp/tpch-approved-plan/**
      # - name: Gluten CPP Benchmark Test
      #   run: |
      #     # This test depends on example.json generated by the above mvn test.
      #     cd $GITHUB_WORKSPACE/cpp/build/velox/benchmarks && \
      #     ./generic_benchmark --run-example --with-shuffle --threads 1 --iterations 1

