# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM quay.io/centos/centos:stream9


ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk
ENV PATH=$JAVA_HOME/bin:$PATH
ENV PATH=${PATH}:/usr/lib/maven/bin

# An actual path used for vcpkg cache.
ENV VCPKG_PATH=/var/cache/vcpkg
# Set vcpkg cache path.
ENV VCPKG_BINARY_SOURCES=clear;files,${VCPKG_PATH},readwrite

RUN set -ex; \
    yum update -y && yum install -y epel-release sudo dnf && yum install -y ccache; \
    dnf install -y --setopt=install_weak_deps=False gcc-toolset-12; \
    echo "check_certificate = off" >> ~/.wgetrc; \
    yum install -y java-17-openjdk-devel patch wget git perl; \
    dnf clean all; \
    git clone --depth=1 https://github.com/apache/incubator-gluten /opt/gluten; \
    cd /opt/gluten && bash ./dev/vcpkg/setup-build-depends.sh; \
    mkdir -p ${VCPKG_PATH}; \
    echo "Build arrow, then install the native libs to system paths and jar package to .m2/ directory."; \
    if [ "$(uname -m)" = "aarch64" ]; then \
        export CPU_TARGET="aarch64"; \
        export VCPKG_FORCE_SYSTEM_BINARIES=1; \
    fi; \
    source /opt/rh/gcc-toolset-12/enable; \
    cd /opt/gluten; \
    bash ./dev/builddeps-veloxbe.sh --enable_vcpkg=ON --build_tests=ON --enable_s3=ON --enable_gcs=ON \
                                    --enable_hdfs=ON --enable_abfs=ON  build_arrow; \
    mvn dependency:go-offline -Pbackends-velox -Piceberg -Pdelta -Pspark-3.5 -DskipTests; \
    rm -rf /opt/gluten; \
    rm -rf /root/.cache/ccache;
