# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM centos:8 as base0

FROM base0 as base
RUN /usr/bin/sed -i -e "s|mirrorlist=|#mirrorlist=|g" /etc/yum.repos.d/CentOS-*; sed -i -e "s|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g" /etc/yum.repos.d/CentOS-*;
RUN yum update -y && yum install epel-release wget perl git bzip2 -y && yum install -y gcc-toolset-11;

# texinfo
FROM base as texinfo
RUN curl -kLO https://ftp.gnu.org/gnu/texinfo/texinfo-6.8.tar.xz
RUN tar xf texinfo*.tar.*
WORKDIR build-texinfo
RUN yum -y install gcc make m4
RUN ../texinfo*/configure
RUN make -j$(nproc)
RUN make install

# Binutils
FROM texinfo as binutils
RUN curl -LO https://ftp.wayne.edu/gnu/binutils/binutils-2.41.tar.xz
RUN sha256sum binutils*.tar.*
RUN echo "ae9a5789e23459e59606e6714723f2d3ffc31c03174191ef0d015bdf06007450 " binutils*.tar.* | sha256sum -c -
RUN tar xf binutils*.tar.*
WORKDIR build-binutils
RUN yum -y install gcc-c++ make zlib-devel gettext bison
RUN ../binutils*/configure
RUN make -j$(nproc)
RUN make install

FROM binutils as gcc
RUN wget https://ftp.gnu.org/gnu/gcc/gcc-13.4.0/gcc-13.4.0.tar.gz && tar -xf gcc-13.4.0.tar.gz && cd gcc-13.4.0; \
    ./contrib/download_prerequisites; \
    mkdir build && cd build ; \
    source /opt/rh/gcc-toolset-11/enable; \
    ../configure --disable-multilib --enable-languages=c,c++; \
   make -j $(nproc) && make install
RUN echo -e '/usr/local/lib\n/usr/local/lib64' > /etc/ld.so.conf.d/local.conf && ldconfig
RUN yum remove gcc -y